syntax = "proto3";

option csharp_namespace = "Driver.Infrastructure.Grpc";

package driver;

service DriverService {
  rpc GetDriverInfo (GetDriverInfoRequest) returns (DriverResponse);
  
  rpc IsDriverAvailable (IsDriverAvailableRequest) returns (IsDriverAvailableResponse);

  rpc GetAvailableDrivers(AvailableDriversRequest) returns (AvailableDriversList);
}

message AvailableDriversRequest {
  repeated string driver_id = 1;
}

message AvailableDriversList {
  repeated DriverResponse drivers = 1;
}

message GetDriverInfoRequest {
  string driver_id = 1;
}

message DriverResponse {
  string driver_id = 1;
  string name = 2;
  string email = 3;
  string status = 4;
  // Note: Set to double on purpose. Should be decimal!
  double fare = 5;
}

message IsDriverAvailableRequest {
  string driver_id = 1;
}

message IsDriverAvailableResponse {
  bool is_available = 1;
}
