<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Driver.Application\Driver.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="11.0.0-preview.2.26159.112"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0"/>
        <PackageReference Include="RabbitMQ.Client" Version="7.2.1"/>
        <PackageReference Include="WolverineFx" Version="5.18.1"/>
        <PackageReference Include="WolverineFx.RabbitMQ" Version="5.18.1"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
