// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ride.Infrastructure.Persistence;

#nullable disable

namespace Ride.Infrastructure.Migrations
{
    [DbContext(typeof(RideDbContext))]
    partial class RideDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ride.Domain.Entities.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("rides", (string)null);
                });

            modelBuilder.Entity("Ride.Domain.Entities.Ride", b =>
                {
                    b.OwnsOne("Ride.Domain.ValueObjects.Location", "Destination", b1 =>
                        {
                            b1.Property<Guid>("RideId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("destination_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("destination_longitude");

                            b1.HasKey("RideId");

                            b1.ToTable("rides");

                            b1.WithOwner()
                                .HasForeignKey("RideId");
                        });

                    b.OwnsOne("Ride.Domain.ValueObjects.Location", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("RideId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_longitude");

                            b1.HasKey("RideId");

                            b1.ToTable("rides");

                            b1.WithOwner()
                                .HasForeignKey("RideId");
                        });

                    b.OwnsOne("Ride.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("RideId")
                                .HasColumnType("uuid");

                            b1.Property<double>("_amount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(0.0)
                                .HasColumnName("price");

                            b1.Property<string>("_currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("USD")
                                .HasColumnName("currency");

                            b1.HasKey("RideId");

                            b1.ToTable("rides");

                            b1.WithOwner()
                                .HasForeignKey("RideId");
                        });

                    b.OwnsOne("Ride.Domain.ValueObjects.Money", "ProposedPrice", b1 =>
                        {
                            b1.Property<Guid>("RideId")
                                .HasColumnType("uuid");

                            b1.Property<double>("_amount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(0.0)
                                .HasColumnName("proposed_price");

                            b1.Property<string>("_currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("USD")
                                .HasColumnName("proposed_currency");

                            b1.HasKey("RideId");

                            b1.ToTable("rides");

                            b1.WithOwner()
                                .HasForeignKey("RideId");
                        });

                    b.Navigation("Destination")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("ProposedPrice")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
