<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Ride.Domain\Ride.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="MediatR" Version="14.1.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Events\Consumers\"/>
        <Folder Include="Rides\Commands\AcceptRide\"/>
        <Folder Include="Rides\Commands\CancelRide\"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
