syntax = "proto3";

option csharp_namespace = "Ride.Infrastructure.Grpc";

package proto;

service LocationService {
  rpc GetNearestAvailableDrivers (NearestDriversRequest) returns (NearestDriversResponse);
  rpc GetPassengerLocation (GetLocationRequest) returns (LocationResponse);
  rpc GetDriverLocation (GetLocationRequest) returns (LocationResponse);
}

message NearestDriversRequest {
  double longitude = 1;
  double latitude = 2;
  optional double radius = 3;
}

message NearestDriversResponse {
  repeated DriverLocation drivers = 1;
} 

message DriverLocation {
  string driver_id = 1;
  double distance = 2;
}

message GetLocationRequest {
  string entity_id = 1;
}

message LocationResponse {
  double latitude = 1;
  double longitude = 2;
}